apiVersion: v1
kind: Service
metadata:
  name: codework-checkin
spec:
  selector:
    app.kubernetes.io/name: codework-checkin
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codework-checkin
  labels:
    name: codework-checkin
spec:
  replicas: 1
  selector:
    matchLabels:
      service: codework-checkin
  template:
    metadata:
      labels:
        service: codework-checkin
    spec:
      containers:
      - name: user-api
        image: 514378342278.dkr.ecr.us-east-1.amazonaws.com/codework-checkin:1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          value: app-db
      restartPolicy: Always
